### ISSUE TITLE
prevent default event

### ISSUE THREAD

**Issue by AlexRevin** [wangzuo/react-input-slider#2]
```
handleDrag: function handleDrag(e) {
    e.preventDefault();
    var rect = this.getDOMNode().getBoundingClientRect();
```

Otherwise it starts making text and element selections

**Comment by wangzuo** [comment]
Its also possible with `user-select: none` through css, what do you think?

**Comment by AlexRevin** [comment]
Don't like this idea, as user-select: none just makes the elements unselectable, however the issue itself is  in event being propagated furthermore, which is absolutely not needed.

It can lead to many other issues, not with selection only.

**Comment by wangzuo** [comment]
released, thanks!
