### ISSUE TITLE
help with redux please? 

### ISSUE THREAD

**Issue by zilahir** [wangzuo/react-input-slider#36]
Hey! 

Sorry for creating an issue here, but I am just unable to solve this, and don't know where else to go for help. 

So, i am using this component, two of them actually. I would like to use redux for store, and it almost working but not 100%. :( 

The issue is, that whenever I am updating one of the sliders, both. of them are reciving the new X props. 

I have pushed my code into a github repo: https://github.com/zilahir/mood-slider

Here's a gif about what is actually happening: 

https://giphy.com/gifs/react-redux-1lBGQerOeLmSO3G4T8

Any help would be highly appreciated.

**Comment by wangzuo** [comment]
seems working now
