### ISSUE TITLE
Stop Propagation

### ISSUE THREAD

**Issue by wayofthefuture** [wangzuo/react-input-slider#40]
Is there any way to access the "Event" object in the onChange handler so I can stop propagation? The problem is we have the slider inside of a React modal component. When we slide the slider the event bubbles up to the parent component.

Currently we are using window.event to catch the event in the onChange handler because we have no way of getting to the Event object from within the callback to stop the propagation of the event. Thanks.

**Comment by wangzuo** [comment]
Have you tried add `preventDefault` to onClick handler, the onChange handler does not send the event object.

**Comment by wayofthefuture** [comment]
Does the onClick handler fire when the slider is being dragged?

**Comment by wangzuo** [comment]
I am not sure but some snippet may help.
