### ISSUE TITLE
Slider output value keeps adding a zero

### ISSUE THREAD

**Issue by Quirksmode** [wangzuo/react-input-slider#41]
The slider always seems to add an extra zero on the end of it's output value. 0 becomes 00, 1 becomes 10, 10 becomes 100. Not sure if it's a bug or something I am missing? 

`
const onChange = (x) => {
    setState(newstate => ({ ...newstate, x }));
};

<InputSlider
          axis="x"
          x={ state.x }
          onChange={ ({ x }) => onChange(x) }
          xstep="0.1"
          xmin="0"
          xmax="1"
        />

`

**Comment by wangzuo** [comment]
Here is an example for floating numbers, props need to be set as numbers.

```javascript
<Slider
  axis="x"
  xstep={0.1}
  xmin={0}
  xmax={1}
  x={state.x}
  onChange={({ x }) => setState({ x: parseFloat(x.toFixed(2)) })}
/>
```

**Comment by Quirksmode** [comment]
I tried, but it didn't work for me sadly. I used the following code:

x = Number.parseFloat(x).toFixed(2);

It had the same issue.

**Comment by wangzuo** [comment]
I have updated an example on https://swiftcarrot.dev/react-input-slider, are you using the latest version?

**Comment by Quirksmode** [comment]
I am using latest version, but still this does not work for me, I always get the following error:

'x.toFixed is not a function'

**Comment by wangzuo** [comment]
xstep, xmin and xmax should be numbers
