### ISSUE TITLE
multi handle range select?

### ISSUE THREAD

**Issue by frankleng** [wangzuo/react-input-slider#5]
can this support multiple handles to select a specific range?

**Comment by wangzuo** [comment]
you mean two handles for a range selection?

**Comment by frankleng** [comment]
@wangzuo two, or perhaps more. like https://mpowaga.github.io/react-slider/

**Comment by wangzuo** [comment]
maybe `react-slider` is a better choice for you?

**Comment by frankleng** [comment]
lol. right on

**Comment by wangzuo** [comment]
:ok_hand:
