### ISSUE TITLE
Cannot read property 'getBoundingClientRect' of null

### ISSUE THREAD

**Issue by mattbucci** [wangzuo/react-input-slider#7]
Slider is totally broken on my install,

Cannot read property 'getBoundingClientRect' of null shows up whenever the slider is clicked

![screen shot 2016-04-28 at 5 55 41 pm](https://cloud.githubusercontent.com/assets/3284147/14905907/7e09f3ac-0d6a-11e6-8a2c-7f0046b9cf07.jpg)

**Comment by wangzuo** [comment]
May need more sample code.
