### ISSUE TITLE
Set the input value programmatically

### ISSUE THREAD

**Issue by txfs19260817** [wangzuo/react-input-slider#83]
Hi, thanks for the great slider! I am working on designing an audio progress bar with this slider component, hoping that when `onTimeUpdate` event of `<audio>` is triggered, the value of slider (or say the position of thumb) can be updated. Could you please provide a solution to set the value of slider programmatically, even if the width style can be controlled but the true value. Thanks!

**Comment by wangzuo** [comment]
This component works as a react controlled input, so a state value would work in you case.

**Comment by txfs19260817** [comment]
Definitely, it works. Thank you so much!

```
const [progress, setProgress] = useState(.0);

<audio ref={playerRef} onTimeUpdate={e => setProgress(e.target.currentTime)}/>

<Slider
    disabled={playerRef.current == null}
    axis="x"
    x={progress}
    xmax={playerRef.current == null ? 100 : playerRef.current.duration}
    xstep={.1}
    onChange={({x}) => {
        setProgress(x)
        playerRef.current.currentTime = x
    }}/>
```
